from fastapi import APIRouter
from app.api.v1.routes import admissions,agents,applications,career,chat,college_matching,connectors,data_ingestion,education,ingestion,jobs,journey,knowledge,notifications,proactive,recommendations,retrieval,scholarships,source_intelligence,sources,student_intelligence,students,tool_search,workflows
api_router=APIRouter()
api_router.include_router(students.router,prefix="/students",tags=["students"])
api_router.include_router(student_intelligence.router,prefix="/student-intelligence",tags=["student-intelligence"])
api_router.include_router(applications.router,prefix="/applications",tags=["applications"])
api_router.include_router(notifications.router,prefix="/notifications",tags=["notifications"])
api_router.include_router(proactive.router,prefix="/proactive",tags=["proactive"])
api_router.include_router(admissions.router,prefix="/admissions",tags=["admissions"])
api_router.include_router(career.router,prefix="/career",tags=["career"])
api_router.include_router(college_matching.router,prefix="/colleges",tags=["college-matching"])
api_router.include_router(scholarships.router,prefix="/scholarships",tags=["scholarships"])
api_router.include_router(chat.router,prefix="/chat",tags=["chat"])
api_router.include_router(knowledge.router,prefix="/knowledge",tags=["knowledge"])
api_router.include_router(education.router,prefix="/education",tags=["education-data"])
api_router.include_router(source_intelligence.router,prefix="/source-intelligence",tags=["source-intelligence"])
api_router.include_router(retrieval.router,prefix="/retrieval",tags=["retrieval"])
api_router.include_router(tool_search.router,prefix="/tools",tags=["tools"])
api_router.include_router(sources.router,prefix="/sources",tags=["knowledge-sources"])
api_router.include_router(connectors.router,prefix="/connectors",tags=["connectors"])
api_router.include_router(jobs.router,prefix="/jobs",tags=["jobs"])
api_router.include_router(ingestion.router,prefix="/ingestion",tags=["ingestion"])
api_router.include_router(data_ingestion.router,prefix="/data-ingestion",tags=["data-ingestion"])
api_router.include_router(recommendations.router,prefix="/recommendations",tags=["recommendations"])
api_router.include_router(agents.router,prefix="/agents",tags=["agents"])
api_router.include_router(journey.router,prefix="/journey",tags=["journey"])
api_router.include_router(workflows.router,prefix="/workflows",tags=["workflows"])
