from app.models.base import Base
from app.models.student import StudentProfile,StudentInterest,StudentSkill,CareerGoal
from app.models.student_intelligence import StudentAcademicRecord,StudentConstraint,StudentIntelligenceSnapshot,StudentMemory
from app.models.application import Application,ApplicationTask,ApplicationDocument,ApplicationEvent
from app.models.knowledge import DataSource,SourceDocument,KnowledgeClaim
from app.models.education import Country,Institution,Course,Program,Scholarship,EntranceExam,EducationFact
from app.models.source_intelligence import SourceProfile,SourceRun
from app.models.retrieval import KnowledgeEmbedding,RetrievalAudit
from app.models.agent_execution import AgentExecution,AgentTaskExecution
from app.models.recommendation import RecommendationRun,RecommendationItem
from app.models.jobs import BackgroundJob
